name: Run Pytest on Push and PR

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies      
        run: |
          python -m pip install --upgrade pip
          pip install git+https://${{ secrets.GH_PAT }}@github.com/bcptraining/pysnowflakepipeline.git@b0e7b25606ce574574929c77840447d38f44baae#egg=snow_pipeline_pkg
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --disable-warnings --maxfail=3

      - name: Run coverage
        run: |
          coverage run -m pytest
          coverage report
