name: Run Pytest on Push and PR

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.13'

      - name: Install dependencies      
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package (editable)
        run: pip install -e .
               
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run coverage
        run: |
          coverage run -m pytest --disable-warnings --maxfail=3
          coverage report
          coverage xml
      - name: Run flake8
        run: flake8 snow_pipeline_pkg tests
